### ISSUE TITLE
Deprecated function: preg_quote() in redis.path.inc

### ISSUE THREAD

**Issue by tkcent** [backdrop-contrib/redis#1]
`Deprecated function: preg_quote(): Passing null to parameter #1 ($str) of type string is deprecated in backdrop_match_path() (line 336 of /website/html/modules/redis/inc/redis.path.inc).`

**Comment by tkcent** [comment]
Line 336:  I believe it should be using 'system.core' instead of 'system.performance' for the site_frontpage config variable.

Also need to change on Line 305.

**Comment by tkcent** [comment]
Pull request #2 submitted.

**Comment by hosef** [comment]
Thanks for reporting this. I did a quick test on my local test site and everything seems to be working so I have merged the PR.
